{{ cookiecutter.formal_name }}/bootstrap, {{ cookiecutter.formal_name }}/manifest.yml, {{ cookiecutter.formal_name }}/src/bootstrap/Makefile, {{ cookiecutter.formal_name }}/src/bootstrap/main.c
Since building a Flatpak involves building everything from source anyway, this provides a convenient entry point to use a genuine stub app, rather than a shell script wrapping the Python interpreter. 
This matches what is done with macOS and Windows apps. It provides complete control over the interpreter, and isolation from the environment in which the app runs. 
Fixes beeware/briefcase#628
Refs beeware/briefcase#662
Addresses the flatpak edge case mentioned in beeware/briefcase#803.
This PR also enables dynamic linking, and strips unused parts of the bundle. This has the effect of reducing the size of a packaged HelloWorld Toga app from 42MB to 28MB.
=> Use a stub app as the flatpak bootstrap.

{{ cookiecutter.formal_name }}/manifest.yml
As it says in the "Build environment" section at the bottom of [this page](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html), Flatpak module builds are done in a sandbox, so they need to be explicitly given access to the host filesystem. This is necessary in order to install requirements from local directories or files.
=> Add --filesystem=host to app_packages module

{{ cookiecutter.formal_name }}/manifest.yml
- To allow users to install local packages, the host filesystem is exposed to the Flatpak build environment. Disabling the pip cache directory prevents pip installing wheels built against the host system which may be incompatible with other Flatpak layers.
- Fixes beeware/briefcase#858
There may be better fixes (like creating a blocklist of directories not to expose to Flatpak (assuming that's even possible)) but disabling the pip cache directory doesn't actually require wheels to be rebuilt every time. If the requirements file is the same as last time, then the Flatpak build cache is used instead of rerunning `pip install`.
Log excerpt when rebuilding a Flatpak app:
```
[flatcache] Building Flatpak...
Emptying app dir 'build'
Downloading sources
Starting build of com.example.flatcache …
```
=> Disable the pip cache directory when building app

{{ cookiecutter.formal_name }}/src/bootstrap/main.c
Modifications to the Flatpak template to support testing.
This is primarily adding support for the `BRIEFCASE_MAIN_MODULE` testing override; if the environment contains that environment variable, it will be used in preference to the app's default module name.
It also:
* Disables optimisation (this conflicts with pytest, and generally seems to be unnecessary)
* Forces a flush of stdout before starting Python. This seems to resolve some issues with output ordering when running flatpak images.
Refs beeware/briefcase#962
=> Add support for the BRIEFCASE_MAIN_MODULE testing endpoint.

{{ cookiecutter.formal_name }}/manifest.yml, {{ cookiecutter.formal_name }}/src/bootstrap/main.c
Reported via discord:
If a user *doesn't* use a virtual environment, and they build a flatpak, any packages that they have installed in their system are taken into consideration when installing packages into the flatpak.
For example - if the user has toga installed in their system Python (even if it is their user `.local` install), the flatpak *won't* install toga as a dependency, as pip determines that the package is already available.
This can be fixed by using `--target` when doing the pip install. 
This PR introduces an explicit app_packages folder, and `pip install`s into that folder as a target. It also ensures that pip is invoked with the version of Python that is in the Flatpak sandbox, rather than relying on the `pip3` shortcut, which is ambiguous.
=> Force installation of requirements into an app_packages folder.

cookiecutter.json, {{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/manifest.yml, {{ cookiecutter.format }}/{{ cookiecutter.bundle_identifier }}.desktop
Updates all of the locations in the cookiecutter template to make use of `bundle_identifier` instead of manually forming it.
Refs https://github.com/beeware/briefcase/pull/1234
=> Switch to using bundle_identifier

{{ cookiecutter.format }}/briefcase.toml
- CPython 3.11.1 -> 3.11.3
- CPython 3.10.9 -> 3.10.11
- pip 22.3.1 -> 23.1.2
- setuptools 65.6.3 -> 67.7.2
- Add ppc64le-unknown-linux-gnu distributions for CPython 3.9, 3.10, and 3.11
- SQLite 3.40.1 -> 3.41.2
- binutils 2.39 -> 2.40
- LLVM 15.0.7 -> 16.0.3
=> Update standalone Python from 20230116 to 20230507

.github/workflows/ci.yml, {{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/manifest.yml
Add Python 3.12 support, based on the 20231002 release of Python-build-standalone.
The new release includes the use of a clang-specific feature (`-fdebug-default-version=4`); this flag isn't available on gcc, and in order to use clang in the Flatpak container, we'd need to *compile* clang - so this takes the pragmatic approach of patching out that flag from python-config and sysconfig.
=> Add updated support packages and CI for Python 3.12 support.

.github/workflows/ci.yml, tests/apps/verify-pygame/pyproject.toml, tests/apps/verify-toga/pyproject.toml
Always install the latest version of requirements for testing app builds, notably for `pygame`.
Dependent on https://github.com/beeware/.github/pull/59; here is [passing CI](https://github.com/beeware/briefcase-linux-flatpak-template/actions/runs/6630065458/job/18010725638) using it, though. Notice that the most recent CI doesn't really test PyGame at all since it doesn't actually build anything.
=> Install the latest version for requirements in CI

{{ cookiecutter.format }}/manifest.yml
- Run `sed` over "all" `_sysconfigdata_*.py` files in `lib`
- In practice, there should just be one of these...but this avoids the need to understand the Python architecture that's a part of the file name
- Closes beeware/briefcase#1511
- I noticed that the `-fdebug-default-version` flag is only [used](https://github.com/search?q=repo%3Aindygreg%2Fpython-build-standalone%20%20fdebug-default-version&type=code) in the x86-64 builds...so, i guess this could be limited to only running for x86-64 Python...but same same
=> Remove clang config from Python irrespective of arch

{{ cookiecutter.format }}/manifest.yml
- We've had issues with stripping libraries from PyPI before; this disables for Flatpak builds.
- This is noticeably a problem for PySide2...although, PySide6 seemingly survives the stripping....either way, it seems a better policy to leave these libraries as-is
=> Do not strip libraries from PyPI packages

{{ cookiecutter.format }}/manifest.yml
- Update Flatpak manifest to allow access to GPU and sound
- Several of the non-Toga GUI toolkits need at least GPU permissions to run
=> Allow access to GPU and sound

{{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/manifest.yml
- Release [20240107](https://github.com/indygreg/python-build-standalone/releases) [restores](https://github.com/indygreg/python-build-standalone/issues/194) gcc compatibility and no longer [links](https://github.com/indygreg/python-build-standalone/issues/197) `libcrypt.so` for Python 3.8, 3.9, and 3.10.
- https://github.com/beeware/.github/pull/79 should be merged first and this PR's CI should be re-run before merging.
=> Bump Python from 20231002 to 20240107

cookiecutter.json, {{ cookiecutter.format }}/manifest.yml
Adds the ability to pass permissions to the generated Linux Flatpak project.
Refs https://github.com/beeware/briefcase/pull/1599.
Briefcase-Repo: https://github.com/freakboy3742/briefcase.git
Briefcase-Ref: permissions
=> Add extension points for permissions.

{{ cookiecutter.format }}/manifest.yml
- Resolves recent [issues](https://github.com/beeware/briefcase/pull/1689) with building Flatpaks because of changes to PyGObject's build process
- PyGObject seems to have updated from `setup.py` to meson-python
- When meson-python builds PyGObject, it adds the `include` directory that was used to build Python but Standalone Python is reporting that's `/install`....in actuality, we've installed Python in to `/app`
- So, this updates the buildtime installation prefix of `/install` to `/app`
- Additionally, the `cp -r` commands are replaced with `cp --archive` to avoid changing any of the metadata or filesystem layout of Python or the app when they are copied in to the Flatpak
- This issue of buildtime absolute paths is called out in Standalone Python's docs: …
=> Update Python's installation prefix

{{ cookiecutter.format }}/src/bootstrap/main.c
The current stub binary used in a packaged system app returns sys.executable as python3. This is neither correct, nor helpful. 
We can use argv[0] (unlike the system template) because flatpak binaries are always executed inside the container with the full path.
=> Ensure that sys.executable returns the correct value

cookiecutter.json, {{ cookiecutter.format }}/src/bootstrap/main.c
Add support for `BRIEFCASE_DEBUG`, and by extension, improve support for console apps.
Refs beeware/briefcase#1781
=> Add support for BRIEFCASE_DEBUG.

{{ cookiecutter.format }}/briefcase.toml
- Use version [20240726](https://github.com/indygreg/python-build-standalone/releases/tag/20240726) of Standalone Python that includes stripped versions
- Introduces minimum platform version 0.3.20 since stripped versions of Standalone Python only exist for 20240726
- Bumps Python 3.12.3 -> 3.12.4
BRIEFCASE_REPO: https://github.com/rmartin16/briefcase
BRIEFCASE_REF: linux-stripped-python
=> Bump Standalone Python from 20240415 -> 20240726

{{ cookiecutter.format }}/install_requirements.sh, {{ cookiecutter.format }}/manifest.yml
Related to https://github.com/beeware/briefcase/issues/1270
Facilitates configuration of the pip install command arguments by Briefcase or the use of a different package installer altogether without needing to re-process the template or add complex logic to the template (as would be required if the command was templated directly into the manifest).
The default contents of `install_requirements.sh` ensure this can be merged without waiting for Briefcase to support writing into the file (e.g., if a Briefcase version is released between this PR merging and the rest of the linked issue being implemented).
Alternatively, if the maintainers prefer, I can change the file to be blank by default, and we can wait to merge this until the Briefcase change is ready.
=> Decouple Python package install command from manifest

{{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/install_requirements.sh, {{ cookiecutter.format }}/manifest.yml, {{ cookiecutter.format }}/pip_install.py
Related to https://github.com/beeware/briefcase/issues/1270
Follow up to #52
Based on the discussion in this PR to address the linked issue in Briefcase: https://github.com/beeware/briefcase/pull/2059#discussion_r1841597072. This PR depends on changes in 
A desire for a generic interface to define pip install arguments was expressed. Using Python to generate the `pip install` invocation and executing it with `execv` ensures that the method for reading the `pip-options.txt` file as a newline delimited list of command arguments is shell agnostic (e.g., does not rely on bash being the shell in order to use its arrays).
Not entirely sure if this is what y'all had in mind @freakboy3742 and @mhsmith but let me know your thoughts.
=> Use installer args file for pip options

{{ cookiecutter.format }}/src/bootstrap/main.c
As described [here](https://github.com/beeware/briefcase/issues/2195#issuecomment-2727821874), the `app_packages` should be added via `site.addsitedir()` so that `.pth` files are executed correctly.
I tested it with a minimal example project I made for this: [pth-execution-checker](https://github.com/timrid/pth-execution-checker)
Should fix https://github.com/beeware/briefcase/issues/2195, https://github.com/beeware/briefcase/issues/669 and https://github.com/beeware/briefcase/issues/381 for "linux flatpak".
There is also a similar PR for "windows visualstudio": https://github.com/beeware/briefcase-windows-VisualStudio-template/pull/52
=> Add processing of .pth files from "app_packages".

.github/workflows/ci.yml, {{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/manifest.yml, {{ cookiecutter.format }}/src/bootstrap/main.c
Python 3.9 is EOL; 3.14 is now available.
Also includes the fix for locale initialization (see beeware/briefcase-iOS-Xcode-template#57).
Needs to be updated to 3.14.0 final when Astral publishes the package.
=> Drop Python 3.9, add 3.14.

cookiecutter.json, {{ cookiecutter.format }}/manifest.yml
Adds the optional ability for the user to add a base to the `manifest.yml`.
Base is different from runtime. This can help fix PySide, for example, by using https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/ as the base.
```
id: org.kde.PyQtWebEngineApp
runtime: org.kde.Platform
runtime-version: '6.9'
sdk: org.kde.Sdk
base: com.riverbankcomputing.PyQt.BaseApp
base-version: '6.9'
cleanup-commands:
- /app/cleanup-BaseApp.sh
finish-args:
- --env=QTWEBENGINEPROCESS_PATH=/app/bin/QtWebEngineProcess
...
modules:
- name: PyQtWebEngineApp
...
```
Refs:
* https://github.com/beeware/briefcase/pull/2478
* https://github.com/beeware/briefcase/issues/2182
=> Add Flatpak base support
